CREATE TABLE PRODUCTO(ID_PRODUCTO INTEGER AUTO_INCREMENT PRIMARY KEY, DESCRIPCION VARCHAR(120),
MARCA VARCHAR(120), CATEGORIA VARCHAR(80), PRECIO FLOAT );

CREATE TABLE FECHA(ID_FECHA INTEGER AUTO_INCREMENT PRIMARY KEY, DIA INTEGER,  MES INTEGER, 
ANIO INTEGER);

CREATE TABLE ALMACEN( ID_ALMACEN INTEGER AUTO_INCREMENT PRIMARY KEY, NUMERO INTEGER,  
NOMBRE VARCHAR(120), ESTADO VARCHAR(80), MUNICIPIO VARCHAR(80));

CREATE TABLE CAJERO ( ID_CAJERO INTEGER AUTO_INCREMENT PRIMARY KEY,  NOMBRE VARCHAR(80), 
A_PATERNO VARCHAR(80), A_MATERNO VARCHAR(80), SUELDO FLOAT);

CREATE TABLE VENTA(ID_VENTA INTEGER AUTO_INCREMENT PRIMARY KEY,ID_PRODUCTO INTEGER, ID_FECHA INTEGER,  
ID_ALMACEN INTEGER, ID_CAJERO INTEGER, NUM_TRANSACCION INTEGER,
VENTAS_UNIDADES INTEGER,FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),FOREIGN KEY (ID_FECHA) REFERENCES FECHA(ID_FECHA), FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACEN(ID_ALMACEN), FOREIGN KEY (ID_CAJERO) REFERENCES CAJERO(ID_CAJERO));
